apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-job
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: benchmark
          image: pforderique/pytorch-benchmark-cpu
